# Generated by Django 3.2.6 on 2021-09-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_estudiantes_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='rol',
        ),
        migrations.AddField(
            model_name='articulo',
            name='Estudiantes',
            field=models.ManyToManyField(to='home.Estudiantes'),
        ),
    ]
