# Generated by Django 3.2.6 on 2021-09-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tipoestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('B', 'Estudiante')], default='C', max_length=20),
        ),
    ]
