# Generated by Django 3.2.6 on 2021-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210904_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='comentario',
            field=models.CharField(default='', max_length=200),
        ),
    ]
