# Generated by Django 3.2.6 on 2021-09-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_tipo_articulo_autoriza'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
    ]
