# Generated by Django 3.2.7 on 2021-09-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_tipo_articulo_autoriza'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(default='', max_length=30),
        ),
    ]
