# Generated by Django 3.2.6 on 2021-09-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_estudiantes_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
    ]
