# Generated by Django 3.2.6 on 2021-09-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_administradores_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='carnet',
            field=models.CharField(default='', max_length=200),
        ),
    ]
