# Generated by Django 3.2.6 on 2021-09-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articulo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tipoestudiante'),
        ),
    ]
